apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpcalchub-register-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpcalchub-register-producer
  template:
    metadata:
      labels:
        app: mpcalchub-register-producer
    spec:
      containers:
      - name: mpcalchub-register-producer
        image: mpcalchub-register-producer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: mpcalc-config
