apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpcalchub-delete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpcalchub-delete
  template:
    metadata:
      labels:
        app: mpcalchub-delete
    spec:
      containers:
      - name: mpcalchub-delete
        image: mpcalchub-delete:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: mpcalc-config
